### PR TITLE
Just target blank added

### PR DESCRIPTION
**Pull request by farshad-vgr**
Just target="_blank" added to <a> tags

### CODE REVIEW

**Comment by farshad-vgr** [comment]
Also, I had a problem with "respinner" on page.js and I changed the import path to '../../src/index' because "respinner" can't be resolved:

Untitled

**Comment by huozhi** [comment]
@farshad-vgr you need to build the pack first: either `pnpm run build` or `pnpm run build:watch` in another terminal thread

**Comment by huozhi** [comment]
Thanks for the PR!

**Comment by farshad-vgr** [comment]
> @farshad-vgr you need to build the pack first: either `pnpm run build` or `pnpm run build:watch` in another terminal thread

Yeeeeeeeah
pnpm fixed the problem
Thank you huozhi very much for your help
That was my first PR experience :-))))
I'm going to create a new loading component soon

**Comment by huozhi** [comment]
Looking forward to see your library 🚀

**Pull request merged**
